config/routes.rb
Rails.application.routes.draw do
  resources :medicamentos
  resources :users
  
  root 'medicamentos#index'

end

app/models/medicamento.rb
class Medicamento < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :medicamentos  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/medicamentos_controller.rb
class MedicamentosController < ApplicationController
  before_action :set_medicamento, only: [:show, :edit, :update, :destroy]

  # GET /medicamentos
  # GET /medicamentos.json
  def index
    @medicamentos = Medicamento.all
  end

  # GET /medicamentos/1
  # GET /medicamentos/1.json
  def show
  end

  # GET /medicamentos/new
  def new
    @medicamento = Medicamento.new
    @users = User.all.map {|user| [user.nombre, user.id]}
  end

  # GET /medicamentos/1/edit
  def edit
  end

  # POST /medicamentos
  # POST /medicamentos.json
  def create
    @medicamento = Medicamento.new(medicamento_params)

    respond_to do |format|
      if @medicamento.save
        format.html { redirect_to @medicamento, notice: 'Medicamento was successfully created.' }
        format.json { render :show, status: :created, location: @medicamento }
      else
        format.html { render :new }
        format.json { render json: @medicamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicamentos/1
  # PATCH/PUT /medicamentos/1.json
  def update
    respond_to do |format|
      if @medicamento.update(medicamento_params)
        format.html { redirect_to @medicamento, notice: 'Medicamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicamento }
      else
        format.html { render :edit }
        format.json { render json: @medicamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicamentos/1
  # DELETE /medicamentos/1.json
  def destroy
    @medicamento.destroy
    respond_to do |format|
      format.html { redirect_to medicamentos_url, notice: 'Medicamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicamento
      @medicamento = Medicamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicamento_params
      params.require(:medicamento).permit(:nombre, :descripcion, :componentes, :dosis, :uso, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:usuario, :nombre, :apellidos, :telefono, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medicamentos_helper.rb
module MedicamentosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/medicamentos/_form.html.erb
<%= form_for(@medicamento) do |f| %>
  <% if @medicamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medicamento.errors.count, "error") %> prohibited this medicamento from being saved:</h2>

      <ul>
      <% @medicamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :componentes %><br>
    <%= f.text_area :componentes %>
  </div>
  <div class="field">
    <%= f.label :dosis %><br>
    <%= f.text_area :dosis %>
  </div>
  <div class="field">
    <%= f.label :uso %><br>
    <%= f.text_area :uso %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select :user_id, options_for_select(@users) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medicamentos/edit.html.erb
<h1>Editing Medicamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @medicamento %> |
<%= link_to 'Back', medicamentos_path %>

app/views/medicamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Medicamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Componentes</th>
      <th>Dosis</th>
      <th>Uso</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicamentos.each do |medicamento| %>
      <tr>
        <td><%= medicamento.nombre %></td>
        <td><%= medicamento.descripcion %></td>
        <td><%= medicamento.componentes %></td>
        <td><%= medicamento.dosis %></td>
        <td><%= medicamento.uso %></td>
        <td><%= medicamento.user.nombre %></td>
        <td><%= link_to 'Show', medicamento %></td>
        <td><%= link_to 'Edit', edit_medicamento_path(medicamento) %></td>
        <td><%= link_to 'Destroy', medicamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medicamento', new_medicamento_path %>

app/views/medicamentos/new.html.erb
<h1>New Medicamento</h1>

<%= render 'form' %>

<%= link_to 'Back', medicamentos_path %>

app/views/medicamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @medicamento.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @medicamento.descripcion %>
</p>

<p>
  <strong>Componentes:</strong>
  <%= @medicamento.componentes %>
</p>

<p>
  <strong>Dosis:</strong>
  <%= @medicamento.dosis %>
</p>

<p>
  <strong>Uso:</strong>
  <%= @medicamento.uso %>
</p>

<p>
  <strong>User:</strong>
  <%= @medicamento.user.nombre %>
</p>

<%= link_to 'Edit', edit_medicamento_path(@medicamento) %> |
<%= link_to 'Back', medicamentos_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellidos %><br>
    <%= f.text_field :apellidos %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Telefono</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.usuario %></td>
        <td><%= user.nombre %></td>
        <td><%= user.apellidos %></td>
        <td><%= user.telefono %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @user.usuario %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @user.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @user.apellidos %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @user.telefono %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>